<a href="https://colab.research.google.com/github/suwisitlk/229352-StatisticalLearning/blob/main/Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [34]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [35]:
a = torch.tensor(2)
a

tensor(2)

In [36]:
b = torch.tensor(3)
a * b

tensor(6)

### Convert a tensor to scalar

In [37]:
c = b.item()
c

3

### Creating 2D tensor

In [38]:
A = torch.tensor([[1, 2], [5, 6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [39]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [40]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [41]:
torch.cuda.is_available()

True

In [42]:
C.device

device(type='cpu')

In [43]:
# copy C to GPU (cuda)
D  = C.cuda()
D.device

device(type='cuda', index=0)

In [44]:
E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

## Basic operations

In [45]:
E * 2

array([[ 2,  4],
       [10, 12]])

In [46]:
E - 2

array([[-1,  0],
       [ 3,  4]])

In [47]:
D.cpu() * np.array ([1, 2])

/tmp/ipython-input-4090808032.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array ([1, 2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [48]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [49]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [50]:
A@B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [51]:
A

tensor([[4, 5],
        [8, 9]])

In [52]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [53]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [54]:
b  = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [55]:
i = torch.eye(3)
i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [56]:
R1 = torch.rand(2,3)
R1

tensor([[0.5543, 0.0215, 0.0659],
        [0.9025, 0.0990, 0.3592]])

In [57]:
R2 = torch.randn(2,3)
R2

tensor([[-1.2545, -1.1492, -0.0836],
        [-1.2449,  1.9294, -0.8126]])

In [58]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

### Checking the shape of a tensor

In [59]:
A .shape

torch.Size([2, 2])

In [60]:
A.size()

torch.Size([2, 2])

### Changing the shape of a tensor

In [61]:
u =  torch.arange(6)
u.shape

torch.Size([6])

In [62]:
# fast but ues more memmory
v = u.reshape(2, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [63]:
w = u.view(3,2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [64]:
a = torch.arange(4)
b = torch.arange(4) + 1
c = torch.stack((a, b), axis = 0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [65]:
# concatenate
e = torch.cat([a,b], axis = 0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [66]:
# e = torch.cat([a,b], axis = 1) #error

### Squeezing a tensor (removing an extra dimension)

In [67]:
A = torch.zeros(1, 2 , 3)
B = A.squeeze()

In [68]:
A.shape

torch.Size([1, 2, 3])

In [69]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [70]:
# H.shape = (6, )
C = B.unsqueeze(axis = 0)
C.shape

torch.Size([1, 2, 3])

## Indexing

In [71]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [72]:
torch.inverse(torch.tensor([[2.0, 0.0], [0.0, 5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [73]:
# 1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

print(X.shape)
print(b.shape)
print(e.shape)

torch.Size([200, 7])
torch.Size([8, 1])
torch.Size([200, 1])


In [74]:
X

tensor([[ 1.0847e+00, -4.7021e-01, -1.7142e+00,  ..., -6.0197e-01,
          1.2320e+00,  6.9118e-01],
        [-1.8542e-01,  1.0817e+00, -1.5183e+00,  ...,  1.1177e+00,
          1.1393e+00,  2.2275e-01],
        [-3.1407e-02,  5.7062e-01,  1.4866e+00,  ..., -1.7499e-02,
         -1.5269e+00,  9.8366e-01],
        ...,
        [-3.8245e-01, -4.6563e-01, -1.1078e-01,  ...,  9.5682e-01,
         -5.9549e-04,  1.8034e+00],
        [-2.1125e-01,  1.8400e-01,  1.1674e+00,  ...,  1.0821e+00,
          3.3579e-01,  8.9886e-01],
        [ 5.2617e-01, -2.8834e-01,  3.3945e+00,  ..., -1.9303e-01,
         -1.7194e+00, -1.7715e-01]])

In [75]:
# 2. Create a tensor that contains only 1's with shape `(200, 1)`.
ones = torch.ones(200, 1)
ones.shape

torch.Size([200, 1])

In [76]:
# 3. Modify tensor `X` by adding the tensor in 2. as the first column.
X = torch.cat((ones, X), dim=1)
X.shape

torch.Size([200, 8])

In [77]:
X

tensor([[ 1.0000e+00,  1.0847e+00, -4.7021e-01,  ..., -6.0197e-01,
          1.2320e+00,  6.9118e-01],
        [ 1.0000e+00, -1.8542e-01,  1.0817e+00,  ...,  1.1177e+00,
          1.1393e+00,  2.2275e-01],
        [ 1.0000e+00, -3.1407e-02,  5.7062e-01,  ..., -1.7499e-02,
         -1.5269e+00,  9.8366e-01],
        ...,
        [ 1.0000e+00, -3.8245e-01, -4.6563e-01,  ...,  9.5682e-01,
         -5.9549e-04,  1.8034e+00],
        [ 1.0000e+00, -2.1125e-01,  1.8400e-01,  ...,  1.0821e+00,
          3.3579e-01,  8.9886e-01],
        [ 1.0000e+00,  5.2617e-01, -2.8834e-01,  ..., -1.9303e-01,
         -1.7194e+00, -1.7715e-01]])

4. Compute `y` using the following formula:
$$ y = Xb + e $$

In [78]:
y = torch.matmul(X, b) + e
y.shape

torch.Size([200, 1])

5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$

In [79]:
b_hat = torch.matmul(torch.matmul(torch.inverse(torch.matmul(X.T, X)), X.T), y)

6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$

In [80]:
y_hat = torch.matmul(X, b_hat)

7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [81]:
# tensor to Numpy array
y_np = y.detach().numpy()
y_hat_np = y_hat.detach().numpy()

# calculate MSE:
mse = np.mean((y_np - y_hat_np)**2)
mse

np.float32(0.9629402)